# this should never be used in production and is intended for testing.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kombiner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kombiner
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kombiner
subjects:
- kind: ServiceAccount
  name: kombiner
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kombiner
  apiGroup: rbac.authorization.k8s.io
