# this should never be used in production and is intended for testing.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
data:
  config.yaml: |-
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      resourceName: kombiner-scheduler
    profiles:
    - schedulerName: kombiner-scheduler
      plugins:
        bind:
          enabled:
          - name: PlacementRequestBinder
          disabled:
          - name: "*"
      pluginConfig:
      - name: PlacementRequestBinder
        args:
          timeout: 5s
