apiVersion: v1
kind: Pod
metadata:
  name: pod-name
spec:
  schedulerName: custom-scheduler
  containers:
  - name: nginx
    image: nginx:1.25
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
