name: End-to-end tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  run-end-to-end-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24"

    - name: Create KIND cluster
      uses: helm/kind-action@v1
      with:
        config: .github/workflows/config/kind.yaml

    - name: List all pods in the cluster
      run: kubectl get pods -A
