name: End-to-end tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  run-end-to-end-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24"

    - name: Build images
      run: make build-image

    - name: Create KIND cluster
      uses: helm/kind-action@v1
      with:
        config: .github/workflows/config/kind.yaml
        cluster_name: kind

    - name: Load images into KIND cluster
      run: kind load docker-image kombiner:latest

    - name: Install kombiner helm chart
      run: make install

    - name: Run end-to-end tests
      run: make test-e2e
